/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

/**
 *
 * @author FLAKABOY
 */
public class Editar_escuela extends javax.swing.JPanel {

    /**
     * Creates new form Editar_escuela
     */
    public Editar_escuela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        lbl_turno = new javax.swing.JLabel();
        lbl_municipio = new javax.swing.JLabel();
        lbl_grado = new javax.swing.JLabel();
        lbl_grupo = new javax.swing.JLabel();
        lbl_clave = new javax.swing.JLabel();
        lbl_nombreDire = new javax.swing.JLabel();
        lbl_zona = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_nombreDire1 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        txt_zona = new javax.swing.JTextField();
        txt_grado = new javax.swing.JTextField();
        txt_grupo = new javax.swing.JTextField();
        txt_municipio = new javax.swing.JTextField();
        txt_nombreDire = new javax.swing.JTextField();
        txt_turno = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_Ciclo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_escuelas = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("EDITAR ESCUELA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btn_atras.setBackground(new java.awt.Color(255, 255, 255));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atras{.png"))); // NOI18N
        btn_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        lbl_turno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_turno.setForeground(new java.awt.Color(0, 0, 0));
        lbl_turno.setText("Turno:");
        jPanel1.add(lbl_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        lbl_municipio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_municipio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_municipio.setText("Municipio:");
        jPanel1.add(lbl_municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        lbl_grado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_grado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_grado.setText("Grado:");
        jPanel1.add(lbl_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        lbl_grupo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_grupo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_grupo.setText("Grupo:");
        jPanel1.add(lbl_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        lbl_clave.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_clave.setForeground(new java.awt.Color(0, 0, 0));
        lbl_clave.setText("Clave:");
        jPanel1.add(lbl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lbl_nombreDire.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nombreDire.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombreDire.setText("Nombre del director:");
        jPanel1.add(lbl_nombreDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        lbl_zona.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_zona.setForeground(new java.awt.Color(0, 0, 0));
        lbl_zona.setText("Zona:");
        jPanel1.add(lbl_zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        lbl_Nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Nombre.setText("Nombre");
        jPanel1.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        lbl_nombreDire1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nombreDire1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombreDire1.setText("Ciclo:");
        jPanel1.add(lbl_nombreDire1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, -1, -1));
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 310, -1));
        jPanel1.add(txt_zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 310, -1));
        jPanel1.add(txt_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 310, -1));
        jPanel1.add(txt_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 310, -1));

        txt_municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_municipioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 310, -1));
        jPanel1.add(txt_nombreDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 310, -1));
        jPanel1.add(txt_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 310, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 310, -1));
        jPanel1.add(txt_Ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 310, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sello__2_-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 70));

        btn_Aceptar.setForeground(new java.awt.Color(51, 204, 0));
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comprobado.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, 30));

        Tabla_escuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CLAVE", "NOMBRE", "TURNO", "ZONA", "GRADO", "GRUPO", "MUNICIPIO", "DIRECTOR", "CICLO"
            }
        ));
        jScrollPane1.setViewportView(Tabla_escuelas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, 1000, 250));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo uni (1).png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_municipioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    public javax.swing.JTable Tabla_escuelas;
    public javax.swing.JButton btn_Aceptar;
    public javax.swing.JButton btn_atras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_clave;
    private javax.swing.JLabel lbl_grado;
    private javax.swing.JLabel lbl_grupo;
    private javax.swing.JLabel lbl_municipio;
    private javax.swing.JLabel lbl_nombreDire;
    private javax.swing.JLabel lbl_nombreDire1;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JLabel lbl_zona;
    public javax.swing.JTextField txt_Ciclo;
    public javax.swing.JTextField txt_clave;
    public javax.swing.JTextField txt_grado;
    public javax.swing.JTextField txt_grupo;
    public javax.swing.JTextField txt_municipio;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_nombreDire;
    public javax.swing.JTextField txt_turno;
    public javax.swing.JTextField txt_zona;
    // End of variables declaration//GEN-END:variables
}
